spring.application.name=user-segment-service

spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.url=

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8090

springdoc.swagger-ui.path=/swagger-ui.html